export const colombiaLocations: Record<string, string[]> = {
  "Amazonas": ["Leticia", "Puerto Nariño"],
  "Antioquia": ["Medellín", "Bello", "Itagüí", "Envigado", "Apartadó", "Rionegro", "Turbo", "Caucasia", "Copacabana", "La Estrella", "Sabaneta", "Caldas", "Marinilla", "Guarne", "Carmen de Viboral"],
  "Arauca": ["Arauca", "Arauquita", "Saravena", "Tame"],
  "Atlántico": ["Barranquilla", "Soledad", "Malambo", "Sabanalarga", "Baranoa", "Puerto Colombia", "Galapa"],
  "Bogotá D.C.": ["Bogotá D.C."],
  "Bolívar": ["Cartagena de Indias", "Magangué", "El Carmen de Bolívar", "Turbaco", "Arjona", "Mompós"],
  "Boyacá": ["Tunja", "Duitama", "Sogamoso", "Chiquinquirá", "Paipa", "Puerto Boyacá", "Villa de Leyva", "Moniquirá"],
  "Caldas": ["Manizales", "La Dorada", "Chinchiná", "Villamaría", "Riosucio", "Supía", "Salamina"],
  "Caquetá": ["Florencia", "San Vicente del Caguán", "Cartagena del Chairá", "Puerto Rico", "El Paujil"],
  "Casanare": ["Yopal", "Aguazul", "Paz de Ariporo", "Villanueva", "Tauramena", "Monterrey"],
  "Cauca": ["Popayán", "Santander de Quilichao", "El Tambo", "Puerto Tejada", "Piendamó", "Corinto", "Miranda"],
  "Cesar": ["Valledupar", "Aguachica", "Agustín Codazzi", "Bosconia", "Curumaní", "El Paso", "Pueblo Bello"],
  "Chocó": ["Quibdó", "Istmina", "Tadó", "Condoto", "Bahía Solano", "Nuquí", "Riosucio"],
  "Córdoba": ["Montería", "Santa Cruz de Lorica", "Tierralta", "Cereté", "Sahagún", "Montelíbano", "Planeta Rica"],
  "Cundinamarca": ["Soacha", "Facatativá", "Chía", "Zipaquirá", "Mosquera", "Madrid", "Funza", "Cajicá", "Fusagasugá", "Girardot", "Tocancipá"],
  "Guainía": ["Inírida", "Barranco Minas"],
  "Guaviare": ["San José del Guaviare", "Calamar", "El Retorno"],
  "Huila": ["Neiva", "Pitalito", "Garzón", "La Plata", "Campoalegre", "San Agustín"],
  "La Guajira": ["Riohacha", "Maicao", "Uribia", "San Juan del Cesar", "Fonseca", "Villanueva", "Albania"],
  "Magdalena": ["Santa Marta", "Ciénaga", "Zona Bananera", "Fundación", "El Banco", "Plato", "Aracataca"],
  "Meta": ["Villavicencio", "Acacías", "Granada", "Puerto López", "Puerto Gaitán", "San Martín", "Cumaral"],
  "Nariño": ["Pasto", "Tumaco", "Ipiales", "Túquerres", "Sandoná", "Barbacoas", "El Charco"],
  "Norte de Santander": ["Cúcuta", "Ocaña", "Villa del Rosario", "Los Patios", "Pamplona", "Tibú", "El Zulia"],
  "Putumayo": ["Mocoa", "Puerto Asís", "Orito", "Valle del Guamuez (La Hormiga)", "Villagarzón", "Sibundoy"],
  "Quindío": ["Armenia", "Calarcá", "Montenegro", "La Tebaida", "Quimbaya", "Circasia", "Salento"],
  "Risaralda": ["Pereira", "Dosquebradas", "Santa Rosa de Cabal", "La Virginia", "Belén de Umbría", "Santuario"],
  "San Andrés y Providencia": ["San Andrés", "Providencia"],
  "Santander": ["Bucaramanga", "Floridablanca", "Barrancabermeja", "Girón", "Piedecuesta", "San Gil", "Socorro", "Vélez"],
  "Sucre": ["Sincelejo", "Corozal", "San Marcos", "Tolú", "Sampués", "San Onofre", "Coveñas"],
  "Tolima": ["Ibagué", "Espinal", "Melgar", "Chaparral", "Líbano", "Honda", "Mariquita", "Fresno"],
  "Valle del Cauca": ["Cali", "Buenaventura", "Palmira", "Tuluá", "Yumbo", "Cartago", "Jamundí", "Buga", "Zarzal", "Roldanillo", "Pradera", "Florida", "Candelaria"],
  "Vaupés": ["Mitú", "Carurú", "Taraira"],
  "Vichada": ["Puerto Carreño", "La Primavera", "Santa Rosalía", "Cumaribo"]
};

export const colombiaDepartments = Object.keys(colombiaLocations);
